import { useState, useEffect } from 'react';
// @ts-ignore - The module is generated by Emscripten
import initWasmModule from './wasm/game_core.js';

export function useWasmCore() {
    const [wasmCore, setWasmCore] = useState<any>(null);
    const [wasmModule, setWasmModule] = useState<any>(null);

    useEffect(() => {
        let isMounted = true;
        let coreInstance: any = null;
        async function loadWasm() {
            try {
                const Module = (await initWasmModule({
                    locateFile: (path: string) => {
                        if (path.endsWith('.wasm')) return '/' + path + '?v=' + Date.now();
                        return path;
                    }
                })) as any;
                if (isMounted) {
                    coreInstance = new Module.WasmGameCore();
                    setWasmModule(Module);
                    setWasmCore(coreInstance);
                }
            } catch (err) {
                console.error("Failed to load WASM module:", err);
            }
        }
        loadWasm();
        return () => {
            isMounted = false;
            if (coreInstance && typeof coreInstance.delete === 'function') {
                coreInstance.delete();
            }
        };
    }, []);

    const getHolesArray = (core: any, module: any) => {
        if (!core || !module) return null;
        const pointer = core.getHolesBuffer();
        // 2048 holes * 4 floats (x, y, z, r) = 8192 floats
        return new Float32Array(module.wasmMemory.buffer, pointer, 8192);
    };

    return { wasmCore, wasmModule, getHolesArray };
}
